### PR TITLE
Added new styling to the webpage and drastically improved the UI

### PR DESCRIPTION
**Pull request by Anmol-Prasad**
Hi initially there were issues with the CSS. Now I have added completely new styling. Hope you'd like it. Here is a demo SS
image

### CODE REVIEW

**Comment by Naman-sharma00100** [comment]
Hello I appreciate all the changes, You did a great job, But there have been many commits which are causing conflicts. Also though I love the new look of the website, I would like to keep the original too on which many other people have worked so please can you re send the PR on another branch. I would accept the keep your whole work on another branch. Thank you

**Comment by Naman-sharma00100** [comment]
@Anmol-Prasad

**Comment by Naman-sharma00100** [comment]
Pls send the same PR for the branch- "contributor_anmol".

**Comment by Anmol-Prasad** [comment]
Yes, sure understandable. I'll send the PR with changes

**Pull request closed without merging**
